// Code generated by golangee/eearc; DO NOT EDIT.

// Package usecase contains the domains use cases, usually in a service form, which uses an arbitrary composition of the domains primitives.
package usecase
