// Code generated by golangee/eearc; DO NOT EDIT.

// Package core contains the domains primitives like Entities, Values, Repositories, Services (anemic), Events, aggregate roots (non-anemic) or DTOs.
package core
