# TODO apply is a keyword to denote the plugin and version which evaluates this file and all descendants.
# adl is for 'architecture description language'
apply:
  - arch/modlets/go/adl@0.0.0

Supportiety:
  doc: |
    ... is a crash reporter to collect application crashes or manual submitted bug reports and
    help requests triggered by customers.

