# TODO apply is a keyword to denote the plugin and version which evaluates this file and all descendants.
# wadl is for 'worldiety architecture description language'
apply:
  - arch/modlets/go/wadl@0.0.0

# TODO: Upper case name qualifies as the technical unique name of the entire project.
Supportiety:
  # TODO: ellipsis reuses the name to avoid repetition
  doc: |
    ... is a crash reporter to collect application crashes or manual bug and help reports triggered by users.

