AdminService:
  SetPassword:
    doc: ... updates the associated user password.
    reqt: [ SetPassword ]
    in:
      Id: { type: UserId, doc: ... the unique id }
    out:
      errors:
        - Errors.Other
        - Errors.NotFound
        - IAM/Admin.WeakPassword # TODO how to introduce that?

EventService:
  OnUserAdded:
    in:
      user: { type: UserAddedEvent, doc: ...the user event to process }
    out:
      errors:
        - Errors.Other
        - Errors.NotFound