// Code generated by golangee/eearc; DO NOT EDIT.

package std

// The stereotype of this type is 'dto'.
type TicketBase struct {
	Id UUID

	Title string

	Description string

	// The User that created this ticket.
	Creator UUID

	// The User that should work on this ticket.
	Assignee UUID
}

// The stereotype of this type is 'dto'.
type TicketCreate struct {
}

// The stereotype of this type is 'dto'.
type TicketShow struct {
}

// The stereotype of this type is 'dto'.
type TicketById struct {
}

// The stereotype of this type is 'dto'.
type SpecialThing struct {
	Timestamp int

	User User
}

// The stereotype of this type is 'dto'.
type User struct {
	Id UUID

	Name string
}

// The stereotype of this type is 'dto'.
type UserById struct {
}
