usecases:
  uc01: &uc01
    EN: As a moderator I want to create a new game by entering a name and an optional description so that I can start inviting estimators.
    DE: Als ein Moderator möchte ich ein neues Spiel starten, indem ich...
    scenarios:
      - System user signs in with valid credentials
        EN: >
          Given I’m a logged-out system user
          and I’m on the Sign-In page
          When I fill in the “Username” and “Password” fields with my authentication credentials
          and I click the Sign-In button
          Then the system signs me in.
        DE: ...
      - User searches for an item by its name
        EN: >
          Given that I’m in a role of registered or guest user
          When I open the “Products” page
          Then the system shows me the list of all products
          And the system shows the “Search” section in the right top corner of the screen
          When I fill in the “Search” field with the name of existing item in the product list
          And I click the “Apply” button OR press the Enter key on keyboard
          Then the system shows products in the Search Results section with product names matching entered product name
          And the system shows the number of search results in the top of the Search Results section

  uc02: &uc02
    EN: As a user I want response times below 1 second.

glossar:
  moderator:
    EN: A moderator is a special kind of user which...
    DE: Ein Moderator is ein spezieller Nutzer...

roles:
# this is a security cross-concern?

contexts:
  sharedkernel:

  security:
  bookSearch:
    EN: >
      The bounded context bookSearch provides everything about searching for books. This involves the following
      user roles.
    by: *uc01
  book-loaning:
    by: *uc02
# Application 

## Bounding Context: