// Code generated by golangee/eearc; DO NOT EDIT.

package supportietyserver

import (
	json "encoding/json"
	flag "flag"
	fmt "fmt"
	os "os"
)

// Configuration contains all aggregated configurations for the entire application and all contained bounded contexts.
type Configuration struct {
}

// Reset restores this instance to the default state.
func (c *Configuration) Reset() {
}

// ConfigureFlags configures the flags to be ready to get evaluated.
func (c *Configuration) ConfigureFlags(flags *flag.FlagSet) {
}

// ParseEnv tries to parse the environment variables into this instance.
func (c *Configuration) ParseEnv() error {

	return nil
}

// ParseFile tries to parse a json file into this instance. Only the defined values are overridden.
//
// Example JSON
//
//   {}
func (c *Configuration) ParseFile(filename string) error {
	file, err := os.Open(filename)
	if err != nil {
		return fmt.Errorf("cannot open configuration file: %w", err)
	}

	defer file.Close() // intentionally ignoring read-only error on close

	dec := json.NewDecoder(file)
	if err := dec.Decode(c); err != nil {
		return fmt.Errorf("cannot decode json: %w", err)
	}

	return nil
}
