// Code generated by golangee/eearc; DO NOT EDIT.

// Package supportietyserver defines the application and dependency injection layer for the 'supportiety_server' executable.
package supportietyserver
